---
# avail range 129.104.6.212 129.104.6.221
all:
  children:
    new_bbone:
      hosts:
        bbone:
          ansible_host: 192.168.6.2
          host_entry: "bbone-aile0.lab-lpp.local"
          ansible_user: debian
          ansible_password: temppwd
          ansible_become: yes
          ansible_become_password: temppwd

    installed_bbones:
      hosts:
        bbone-aile0.lab-lpp.local:
          ansible_host: 129.104.6.212
          desc: beaglebone salle serveurs aile 0
        bbone-01-1008B.lab-lpp.local:
          ansible_host: 129.104.6.213
          desc: beaglebone salle laser Cyril Drag
        bbone-01-1004B.lab-lpp.local:
          ansible_host: 129.104.6.214
          desc: beaglebone salle manip olivier

    uninstalled_bbones:
      hosts:


    all_bbones:
      installed_bbones:
      uninstalled_bbones: